dist: xenial
language: node_js

node_js:
  - lts/*

before_install:
  - go get github.com/nats-io/gnatsd
  - nohup npm run nats > /dev/null 2>&1 &

install: npm ci

cache:
  directories:
  - "$HOME/.npm"

script: nyc npm test && nyc report --reporter=text-lcov | coveralls
